### ISSUE TITLE
BUNDLEPATH_IGNORELIST not working in app versions report

### ISSUE THREAD

**Issue by rickheil** [munkireport/inventory#1]
Tested with 4.0.1 release tag, server running PHP 7.1.25

Expected behavior: when a path is added to the BUNDLEPATH_IGNORELIST variable in .env, the App Versions report and Inventory Listing should ignore any bundles that are in that regex path. For example, if munki runs on an autopkg machine it should ignore anything in */Library/AutoPkg.

Actual behavior: The BUNDLEPATH_IGNORELIST .env variable does not seem to affect the paths, and even the pieces in the array in config.php (specifically the AutoPkg folder exclude) do not seem to be ignored. Bundles in */Library/AutoPkg for example are showing in both the App Versions report and the Inventory Listing.

**Comment by bochoven** [comment]
I can replicate the issue, now trying to resolve it.

**Comment by bochoven** [comment]
It looks like the .env parser is tripping over backslashes.
`.*\\.app\\/.*\\.app` parses fine as `.*\.app\/.*\.app` does not.

**Comment by rickheil** [comment]
﻿Interesting. What characters do we need to be escaping for this? The old config.php system didn’t need any escaping if I remember right (which is probably why my .env file doesn’t have any).

**Comment by bochoven** [comment]
Yes, that is the issue. phpdotenv 2.x is silently removing the string. phpdotenv 3.x gives a traceback which would help identify the issue. We need some documentation about escaping backslashes in a .env file

**Comment by bochoven** [comment]
Updated the Dotenv library and added exception handling for badly formatted variables
