### ISSUE TITLE
Inventory reports failing due to out of range error

### ISSUE THREAD

**Issue by matt-cahill** [munkireport/inventory#10]
Our clients have started reporting the following error which is preventing new inventory report data from being uploaded to munkireport.

```
SQLSTATE[22003]: Numeric value out of range: 167 Out of range value for column 'id' at row 1
```

The issue appears to be that the `id` column in the table is an unsigned int(10) and the the incremented `id` has reached the maximum value.

```
inventoryitem | CREATE TABLE `inventoryitem` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `serial_number` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `version` varchar(78) COLLATE utf8_unicode_ci NOT NULL,
  `bundleid` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `bundlename` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `path` text COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `inventoryitem_name_version_index` (`name`,`version`),
  KEY `inventoryitem_serial_number_index` (`serial_number`),
  KEY `inventoryitem_bundleid_index` (`bundleid`),
  KEY `inventoryitem_bundlename_index` (`bundlename`)
) ENGINE=InnoDB AUTO_INCREMENT=4294967446 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```

```
MariaDB [munki]> select id from inventoryitem order by id desc limit 3;
+------------+
| id         |
+------------+
| 4293893628 |
| 4293893626 |
| 4293893624 |
+------------+
3 rows in set (0.000 sec)
```
Should we alter this to be a bigint on our DB and does there need to be a DB migration added so others don't hit this?

**Comment by tuxudo** [comment]
Changing this to a bigint is a good fix. Will create a migration for this

**Comment by tuxudo** [comment]
Put this migration in the module's `migrations` folder and run the database migrations in Admin->Upgrade Database. It'll change the `id` column to use bigints. Fix will be included in the Python 3 version (v7.0) of the module. 

https://github.com/munkireport/inventory/blob/mr5-python3/migrations/2023_02_28_000000_inventory_bigint_id.php

**Comment by matt-cahill** [comment]
fantastic, thanks for getting back so quickly @tuxudo

**Comment by matt-cahill** [comment]
ok yeah, that migrated successfully and clients can report again. thanks again.
